"""auth_history

Revision ID: f9f39b7e37e9
Revises: c6a55365e054
Create Date: 2024-06-28 14:19:42.391849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9f39b7e37e9"
down_revision: Union[str, None] = "c6a55365e054"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "authentication_histories", ["id", "user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "authentication_histories", type_="unique")
    # ### end Alembic commands ###
